### ISSUE TITLE
Migrate from SpringFox to SpringDoc

### ISSUE THREAD

**Issue by josdem** [josdem/fruitypedia-spring-boot#37]
As **developer**, I want to migrate to [SpringDoc] (https://springdoc.org/) **so that** I can have the latest Swagger Spring Boot compabilitity

**Acceptance Criteria**
- I am able to see the Spring Doc configuration
- Swagger endpoints are working fine
- I do not see any SpringFox dependencies

**Comment by kirillsinyuk** [comment]
Unfortunately, the latest version of springDoc is not compatible with current springBoot version.
Don't mind if I drop springFox in #37 and then just add springDoc here?

**Comment by josdem** [comment]
> Unfortunately, the latest version of springDoc is not compatible with current springBoot version.
> Don't mind if I drop springFox in #37 and then just add springDoc here?

Sounds good to me, please go for it

**Comment by josdem** [comment]
Deployed to production: https://fruitypedia.josdem.io/categories/en
@kirillsinyuk 🎉
