### ISSUE TITLE
Add error handler in controllers

### ISSUE THREAD

**Issue by josdem** [josdem/fruitypedia-spring-boot#42]
As **developer**, I want to add an error handler in controllers **so that** I can return a `400` error range in case of bad request / item not found

**Acceptance Criteria**
- I can see an error handler in controllers
- I have some test cases covering negative scenario

**Reference**
https://github.com/josdem/shopping-cart-service/blob/main/src/main/java/com/josdem/shopping/cart/controller/ProductController.java

**Comment by traitsisgiorgos** [comment]
hi, I am new, can you give same more info about the issue?

**Comment by josdem** [comment]
> hi, I am new, can you give same more info about the issue?

HI @traitsisgiorgos welcome! Please take a look at this conversation where @kirillsinyuk is describing the issue: https://github.com/josdem/jugoterapia-webflux/issues/35#issuecomment-2000370260
We need to add an error handler to the controller when an element is not found. Also I attached an example of how to implement it.

**Comment by kirillsinyuk** [comment]
As I remember, you don't always need to write your own exceptionHandler.
There are simpler ways to do the same thing.
for example, you can just mark custom NotFoundException with @ResponseStatus annotation upon it.
or you can throw ResponseStatusException.
JFYI

**Comment by josdem** [comment]
We wil cancel this issue, we will go with @kirillsinyuk  approach defined in: https://github.com/josdem/fruitypedia-spring-boot/blob/47d4653a341f42b844b14eeee02016f9153b7146/src/main/java/com/jos/dem/jugoterapia/webflux/controller/BeverageController.java#L46
